name: CI

on:
  push:
    branches: [ "main", "feat/**", "fix/**", "chore/**" ]
  pull_request:

jobs:
  build-test:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash

    steps:
      # Configure git to use LF on Windows
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node (for npm lint/test/build scripts)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install system deps: ShellCheck ≥1.0 & BATS ≥1.10
      - name: Install ShellCheck & BATS (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck zsh fish dash
          # Install bats-core from official Ubuntu repos (available in 22.04+)
          sudo apt-get install -y bats || {
            # Fallback: install from GitHub releases
            echo "Official bats package not available, installing from GitHub releases..."
            curl -sSL https://github.com/bats-core/bats-core/archive/v1.11.0.tar.gz | tar -xzC /tmp
            sudo /tmp/bats-core-1.11.0/install.sh /usr/local
          }

      - name: Install ShellCheck & BATS (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install shellcheck bats-core fish
          # Dash is not in Homebrew core, but we can test with /bin/sh which is similar
          # zsh is pre-installed on macOS but ensure it's available
          which zsh || brew install zsh

      # Windows: Install BATS and run focused integration tests
      - name: Install BATS (Windows)
        if: runner.os == 'Windows'
        run: |
          # BATS for Windows (Git Bash has bash)
          echo "Installing BATS..."
          git clone --depth 1 https://github.com/bats-core/bats-core.git || exit 1
          (cd bats-core && ./install.sh /usr/local) || exit 1
          
          # Verify BATS installation
          /usr/local/bin/bats --version || exit 1
          
          # Add to PATH for npm scripts
          echo "/usr/local/bin" >> $GITHUB_PATH
          export PATH="/usr/local/bin:$PATH"
          
      # Windows: Run focused integration tests
      - name: Windows integration tests
        if: runner.os == 'Windows'
        run: |
          # Set Windows environment
          export OSTYPE="msys"
          export GHS_PERF_MULTIPLIER=3
          export PATH="/usr/local/bin:$PATH"
          
          # Test script loads correctly
          export GHS_STRICT_MODE="false"
          source ./gh-switcher.sh || { echo "❌ Failed to source script"; exit 1; }
          
          # Run ONLY the Windows risk tests
          echo "Running focused Windows integration tests..."
          /usr/local/bin/bats tests/integration/test_windows_risks.bats || {
              echo "❌ Windows integration tests failed"
              exit 1
          }
          
          echo "✅ Windows risk tests passed"

      # Install npm dependencies (none yet, but future-proof)
      - name: Install npm dependencies
        run: npm install --ignore-scripts --no-audit --no-fund

      # Run repository verification sequence (lint → test → build)
      - name: Run lint → test → build
        run: |
          # Windows: Skip full test suite, just run build
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "✅ Windows validation passed (full tests run on Linux/macOS)"
          else
            # Non-Windows: Run full test suite
            npm run lint
            npm test
          fi
          
          # Run build (all platforms)
          npm run build --if-present || exit 1