name: CI

on:
  push:
    branches: [ "main", "feat/**", "fix/**", "chore/**" ]
  pull_request:

jobs:
  build-test:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash

    steps:
      # Configure git to use LF on Windows
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node (for npm lint/test/build scripts)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install system deps: ShellCheck ≥1.0 & BATS ≥1.10
      - name: Install ShellCheck & BATS (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck zsh fish dash
          # Install bats-core from official Ubuntu repos (available in 22.04+)
          sudo apt-get install -y bats || {
            # Fallback: install from GitHub releases
            echo "Official bats package not available, installing from GitHub releases..."
            curl -sSL https://github.com/bats-core/bats-core/archive/v1.11.0.tar.gz | tar -xzC /tmp
            sudo /tmp/bats-core-1.11.0/install.sh /usr/local
          }

      - name: Install ShellCheck & BATS (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install shellcheck bats-core fish
          # Dash is not in Homebrew core, but we can test with /bin/sh which is similar
          # zsh is pre-installed on macOS but ensure it's available
          which zsh || brew install zsh

      # Windows: Just do basic validation
      - name: Basic Windows validation
        if: runner.os == 'Windows'
        run: |
          # Set Windows environment
          export OSTYPE="msys"
          export GHS_PERF_MULTIPLIER=3
          
          # Test script syntax
          bash -n gh-switcher.sh || { echo "❌ Script syntax error"; exit 1; }
          
          # Test script sourcing
          export GHS_STRICT_MODE="false"
          source ./gh-switcher.sh || { echo "❌ Failed to source script"; exit 1; }
          
          # Test basic functionality
          if type cmd_users >/dev/null 2>&1; then
            echo "✅ Windows Git Bash support verified"
          else
            echo "❌ Functions not loaded"
            exit 1
          fi

      # Install npm dependencies (skip Windows due to platform restriction)
      - name: Install npm dependencies
        if: runner.os != 'Windows'
        run: npm install --ignore-scripts --no-audit --no-fund

      # Run repository verification sequence (lint → test → build)
      - name: Run lint → test → build
        run: |
          # Windows: Skip full test suite, just run build
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            echo "✅ Windows validation passed (full tests run on Linux/macOS)"
          else
            # Non-Windows: Run full test suite
            npm run lint
            npm test
          fi
          
          # Run build (skip npm commands on Windows since package isn't installed)
          if [[ "${{ runner.os }}" != "Windows" ]]; then
            npm run build --if-present || exit 1
          fi